# security:
#     # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
#     role_hierarchy:
#         ROLE_ADMIN: [ROLE_USER]

#     encoders:
#         Symfony\Component\Security\Core\User\User
#             algorithm: bcript
#         AppBundle\Entity\Client
#             algorithm: bcrip

#     providers:
#         chain_provider:
#             chain:
#                 providers: [ in_memory, db_provider ]

#             db_provider:
#                 entity:
#                     class: Client
#                     property: user_name

#     firewalls:
#         dev:
#             pattern: ^/(_(profiler|wdt)|css|images|js)/
#             security: false

#         main:
#             pattern: ^/
#             provider: chain_provider

#             form_login:
#                 login_path: login
#                 check_path: login

#             anonymous: ~
#             logout: true